name: Build

on:
  - push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: ./pack.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lmu-ruijie-login
          path: build/*.tar.gz
